version: '3.8'

services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ${HOME}/.cache:/root/.cache  # Cache HF models and datasets
    env_file:
      - .env
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: launch --config-file configs/zero3.yaml --num-processes 1 verifiers/examples/bfcl_agent.py
